# yaml-language-server: $schema=../../../../plugins/plugin_utils/schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  serial_number:
    documentation_options:
      filename: Fabric Topology
    description: |
      Set to the Serial Number of the device
      For now only used for documentation purpose in the fabric documentation.
      "serial_number" can also be set directly as a hostvar.
      If both are set, the setting under "Fabric Topology" takes precedence.
    type: str
    convert_types:
      - int
