---
# This must be the same value for all devices in the molecule scenario.
fabric_name: EOS_DESIGNS_DEPRECATED_VARS

connected_endpoints_keys:
  servers:
    type: server
  firewalls:
    type: firewall
  routers:
    type: router
  load_balancers:
    type: load_balancer
  storage_arrays:
    type: storage_array
