type: pe

pe:
  defaults:
    loopback_ipv4_pool: 10.42.0.0/24
    bgp_as: 42
  nodes:
    - name: node_type_keys
      id: 42

node_type_keys:
  pe:
    type: pe
    mpls_lsr: true
    default_mpls_overlay_role: client
    default_evpn_role: client
    network_services:
      l1: true
      l2: true
      l3: true
    default_overlay_routing_protocol: ibgp
    default_overlay_address_families: [ evpn ]
    default_evpn_encapsulation: mpls
