hostname: network_services_keys_name
router_bgp:
  as: '42'
  router_id: 10.42.0.42
  bgp:
    default:
      ipv4_unicast: false
  maximum_paths:
    paths: 4
    ecmp: 4
  updates:
    wait_install: true
  peer_groups:
  - name: MPLS-OVERLAY-PEERS
    type: mpls
    update_source: Loopback0
    bfd: true
    send_community: all
    maximum_routes: 0
    remote_as: '42'
  address_family_ipv4:
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: false
  address_family_evpn:
    peer_groups: []
  address_family_vpn_ipv4:
    neighbor_default_encapsulation_mpls_next_hop_self:
      source_interface: Loopback0
    peer_groups:
    - name: MPLS-OVERLAY-PEERS
      activate: true
service_routing_protocols_model: multi-agent
ip_routing: true
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
vrfs:
- name: MGMT
  ip_routing: false
- name: TENANT_B_WAN
  tenant: TENANT_B
  ip_routing: true
management_api_http:
  enable_vrfs:
  - name: MGMT
  enable_https: true
loopback_interfaces:
- name: Loopback0
  description: MPLS_Overlay_peering
  shutdown: false
  ip_address: 10.42.0.42/32
  isis_enable: CORE
  isis_passive: true
  node_segment:
    ipv4_index: 42
router_isis:
  instance: CORE
  log_adjacency_changes: true
  net: null
  router_id: 10.42.0.42
  is_type: level-2
  address_family_ipv4:
    enabled: true
    maximum_paths: 4
  advertise:
    passive_only: false
  segment_routing_mpls:
    router_id: 10.42.0.42
    enabled: true
mpls:
  ip: true
router_bfd:
  multihop:
    interval: 300
    min_rx: 300
    multiplier: 3
vlans:
- id: 111
  name: Tenant_A_OP_Zone_2
  tenant: TENANT_B
- id: 160
  name: Tenant_A_VMOTION
  tenant: TENANT_B
ip_igmp_snooping:
  globally_enabled: true
vlan_interfaces:
- name: Vlan111
  tenant: TENANT_B
  tags:
  - opzone
  description: Tenant_A_OP_Zone_2
  shutdown: false
  vrf: TENANT_B_WAN
  ip_helpers:
  - ip_helper: 1.1.1.1
    source_interface: lo100
    vrf: MGMT
