---
# Minimum config to only test the specific feature.
type: spine
spine:
  defaults:
    loopback_ipv4_pool: 10.42.0.0/24
    bgp_as: 42
    vtep_loopback_ipv4_pool: 10.43.0.0/24
  nodes:
    - name: duplicate-interface-l3-edge
      id: 1

l3_edge:
  p2p_links:
    - nodes: [duplicate-interface-l3-edge, peer1]
      interfaces: [ethernet1, ethernet1]
      id: 1
      profile: profile1
      as: [65000, 65002]
      ip: [192.168.0.2/31, 192.168.0.3/31]

    - nodes: [duplicate-interface-l3-edge, peer2]
      # duplicate interface for duplicate-interface-l3-edge
      interfaces: [ethernet1, ethernet2]
      id: 2
      profile: profile2
      as: [65001, 65003]
      ip: [192.168.0.4/31, 192.168.0.5/31]

expected_error_message: >-
  Found duplicate objects with conflicting data while generating configuration for Ethernet Interfaces defined under
  l3_edge p2p_link. {'name': 'ethernet1', 'peer': 'peer2', 'peer_interface': 'ethernet2',
  'description': 'P2P_peer2_ethernet2', 'ip_address': '192.168.0.4/31'} conflicts with
  {'name': 'ethernet1', 'peer': 'peer1', 'peer_interface': 'ethernet1', 'description': 'P2P_peer1_ethernet1',
  'ip_address': '192.168.0.2/31'}.
