type: l3leaf

l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    structured_config:
      sflow:
        vrfs:
          OOB:
            destinations:
              192.168.200.10:
              10.0.200.90:
  node_groups:
    sflow-tests-leaf-mlag:
      bgp_as: 65105
      nodes:
        node_type:
          id: 5
          mgmt_ip: 192.168.0.103/24
