type: l3leaf
l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    id: 101
    bgp_as: 101

platform_speed_groups:
  7280R:
    25G: [ 3, 2 ]
    10G: [ 1, 2, 4 ]
