type: l3leaf
l3leaf:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.254.0/24
    id: 101
    bgp_as: 101

port_profiles:
  TENANT_A_B:
    mode: trunk
    vlans: "110-111,210-211"
